### ISSUE TITLE
nodejs and npm

### ISSUE THREAD

**Issue by TinajaLabs** [j8r/DPlatform#1]
I just installed rocket.chat on a raspi 3 (latest debian, jessie) and it seems to be working perfectly.  A lot happened during that install so your application is valuable for that alone.  Thank you.

My next hope is to install hubot and it requires node.js and npm.  Now I see NPM does not appear to be installed.  I think that nodejs was installed as part of raspian or maybe as part of rocket.chat.

Anyway, when I try to install nodejs through DPlatform, it says it's already installed and bounces out.

I manually installed npm and all is well.  Just thought I would mention a catch-22 in your app; if nodejs is installed then your app will not allow an install of NPM; except manually.

Thanks,
Chris.

**Comment by j8r** [comment]
I thought that installing NodeJS through nodesource will install also npm as a bundle. Thanks, i add npm with nodejs installation :+1:
