### ISSUE TITLE
Issues installing (and updating) Rocket.Chat

### ISSUE THREAD

**Issue by GorgiAstro** [j8r/DPlatform#10]
Hi,

I have some new issues updating Rocket.Chat. The logs below show that the commands "download" and "extract" in the Bash script are not recognized. I have a Raspberry Pi 3 with up-to-date Raspbian Jessie.

useradd: user 'rocketchat' already exists
apps/Rocket.Chat.sh: 97: apps/Rocket.Chat.sh: download: not found
apps/Rocket.Chat.sh: 100: apps/Rocket.Chat.sh: extract: not found
mv: cannot stat ‘bundle’: No such file or directory
rm: cannot remove ‘rocket.chat.tgz’: No such file or directory
apps/Rocket.Chat.sh: 105: cd: can't cd to Rocket.Chat/programs/server
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/home/rocketchat/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/share/meteor/dev_bundle/bin/node" "/usr/share/meteor/dev_bundle/bin/npm" "install"
npm ERR! cwd /home/rocketchat
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /home/rocketchat/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rocketchat/npm-debug.log
npm ERR! not ok code 0
Warning: Unit file of rocket.chat.service changed on disk, 'systemctl daemon-reload' recommended.

**Comment by j8r** [comment]
Hi, thanks to report this issues! I fix this as soon as possible.

**Comment by j8r** [comment]
Could you try it again? It should work now.
