### ISSUE TITLE
Etherpad DirtyDB

### ISSUE THREAD

**Issue by 1xPdd** [j8r/DPlatform#11]
Just tried Etherpad. Seems to install fine; however, starting a new pad gives the following warning:

> Warning: DirtyDB is used. This is fine for testing but not recommended for production. -- To suppress these warning messages change suppressErrorsInPadText to true in your settings.json

Not sure, but I assume it's not ideal to use DirtyDB, so suppressing the warning is probably the wrong thing to do. Anyhow, fyi.

**Comment by 1xPdd** [comment]
Didn't realize I could see the command line output (while installing another package), but Etherpad reported these errors while installing:

> Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> ep_etherpad-lite@1.6.0 /home/etherpad/etherpad-lite/src

**Comment by j8r** [comment]
For the Warns, this is not really problem if it works. Furthermore this not related to DPlatform, but to the [Etherpad project](https://github.com/ether/etherpad-lite).
Anyway on the DirtyDB side, you show a good point, this is not very production-ready. Etherpad supports postgres, sqlite and mysql to set up in `settings.json`. SQlite will be a good choice.

**Comment by 1xPdd** [comment]
That makes sense, thanks.
