### ISSUE TITLE
JitsiMeet

### ISSUE THREAD

**Issue by 1xPdd** [j8r/DPlatform#13]
JitsiMeet installs w/out error to hostname/; however, unable to connect to it in browser. There are not systemd services for it (not sure if there should be), so I'm unable to give error logs. It might be prudent to change default install away from the server root.

**Comment by j8r** [comment]
Sorry for the delay, thanks to notice me of this! I've only followed their [quick-install instructions](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md), nothing more. So no systemd sevices added. You can try to manually install Jitsi Meet, and tell them if you encounter a problem.
