### ISSUE TITLE
Similar projects, fyi

### ISSUE THREAD

**Issue by 1xPdd** [j8r/DPlatform#14]
I discovers a couple similar projects. It might be useful to borrow/team up with/fork them. DPlatform seems the most general, which makes it quite appealing, but the more the merrier.
- DietPi (customized Debian for Raspberry Pi) has an software install script: http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5
- a 'home server' script: https://github.com/igorpecovnik/Debian-micro-home-server
- and an htpc fork of the above: http://www.htpcguides.com/arm-pi-media-server-installer-images-download-page/

**Comment by j8r** [comment]
I just knew Debian-micro-server, they are interessant projects. The two last projects are Raspberry Pi specific. DietPi is the closest of DPlatform. However there are some differences that makes them quite uncompatible. First, the license, DP is MIT vs GPLv2, DP  aims to be a lightweight standalone executable script,  universal across UNIX systems, DietPi is an image based on debian.
By the way DPlatform could maybe be a part of DietPi, and/or htpc-fork and Debian-micro-home-server be merged to DPlatform.

**Comment by 1xPdd** [comment]
Oh, I didn't even think of licensing....

Nor did I realize DP worked outside a Debian-based environment; I just glanced at a couple install files and saw both deb and rpm support. That's quite cool.
