### ISSUE TITLE
Wordpress.sh

### ISSUE THREAD

**Issue by ghost** [j8r/DPlatform#15]
Hi in wordpress.sh, there's an error, when you clone the folder of WP-Quick-Install and then want to run the index.php (line 18 in /app/wordpress.sh) file inside it you miss a subfolder into the path.

`php WP-Quick-Install/index.php`

how it should be

`php WP-Quick-Install/wp-quick-install/index.php`

after editing this line the setup will proceed, but i'm still getting errors when trying to launch nginx:

`[emerg] 32764#0: invalid number of arguments in "try_files" directive in /etc/nginx/sites-enabled/wordpress:19`

doing a `ngnix -t` return that infos

`nginx -t
nginx: [emerg] unknown directive "fastcgi_params" in /etc/nginx/sites-enabled/wordpress:24
nginx: configuration file /etc/nginx/nginx.conf test failed`

so i've commented this line inside the `/etc/nginx/sites-enabled/wordpress`

`# fastcgi_params;`

and based on some internet searches [(Link 1)](https://michaelshadle.com/2009/03/19/finally-using-nginxs-try-files-directive) and [(Link2)](https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-nginx-on-ubuntu-14-04) i've edited this few lines inside the same file:

`line 8: try_files $uri $uri/ /index.php?q=$uri&$args;`
`line 19:  try_files $uri $uri/ /wordpress/index.php?q=$uri&$args;`

Now ngnix service starts but when i'm trying to open the following address `myserverlanipaddress:8089` i'm getting error 403.

**Comment by j8r** [comment]
Thank you to report the issue and your work. I will dig on this way.
