### ISSUE TITLE
Issues while installing Rocket.Chat

### ISSUE THREAD

**Issue by alexjj** [j8r/DPlatform#17]
Fresh OS install, first time running DPlatform and I try to install Rocket.Chat. It gets stuck on the "Define the Rocket.Chat MongoDB database".

I want local but it just reverts back to the define database screen. Both external and local options do nothing and it reverts back to the "Define the Rocket.Chat MongoDB database" menu.

**Comment by Cloudxtreme** [comment]
Same here on CentOS 7

**Comment by j8r** [comment]
Thank you both, I fix this now!
