### ISSUE TITLE
Lancement wget

### ISSUE THREAD

**Issue by tomaklod** [j8r/DPlatform#18]
Une belle installation Debian 8 toute neuve je lance le `wget -qO- https://raw.githubusercontent.com/DFabric/DPlatform-ShellCore/master/init.sh | sudo sh`

et rien..
Une idée ?
Merci d'avance !

**Comment by tomaklod** [comment]
Je me suis rendu compte du problème tout seul haha ! Très beau travail 👍

**Comment by j8r** [comment]
Pas de problèmes :) `sudo` n'était pas installé c'est ca?

**Comment by tomaklod** [comment]
Oui :/ ! haha ! 
Ceci dit j'ai rencontré un autre problème 
quand je tente d'installer certaines apps j'obtient un
`│ You need to use systemd boot system │`

**Comment by j8r** [comment]
Oui. Je vais modifier un peu le message, mais cela veut dire que le système d'init n'est pas systemd et que tu ne pourra pas profiter des services customs fait pour les apps.
Tu es sur d'avoir un systemd opérationnel?
