### ISSUE TITLE
Add Shout

### ISSUE THREAD

**Issue by casdr** [j8r/DPlatform#2]
First of all, great work! I'm always too lazy to set up my own server and this really helps.

Second, I would love to see Shout being added to DPlatform, more information can be found here: http://shout-irc.com/

If I'm able to find some free time, I'll add it myself.

**Comment by j8r** [comment]
Thank you for your feedback! I just see your post luckily in [Reddit](https://www.reddit.com/r/selfhosted/comments/4j5ku4/irccloud_ircanywhere_tapchat_alternative/). You ask exactly what i think, indeed IRCAnywhere is no longer maintained actively, so it's better to find an another alternative.
By the way, i've planned to support [Shout](https://github.com/erming/shout) soon.

**Comment by casdr** [comment]
Ah yep, forgot to update this issue. Shout is indeed a really good alternative.

**Comment by j8r** [comment]
Oh wait Shout is already supported by DPlatform. There is a `apps/Shout.sh` file and an entry on the main installation menu. I just miss to add a description in the `README.md`. I update this now. Thanks, nice catch :)
