### ISSUE TITLE
Rocket.Chat instructions doesn't work anymore

### ISSUE THREAD

**Issue by abers** [j8r/DPlatform#20]
Not sure what went wrong here. I was running rocket.chat when suddenly the server stopped. Tried running "sudo sh init.sh" to check status / restart it but received error message "sh: 0: Can't open init.sh". Restarted device and tried again but receive the same error message.

Thank you.

**Comment by abers** [comment]
Still unsure what happened. Removed DPlatform-ShellCore folder and curl'd it again ran sudo sh init.sh and it opened fine. Though cannot get Rocket.Chat to work again.

**Comment by j8r** [comment]
Rocket Chat have been recently released to 0.40.x that have moved to meteor 1.4 and thus now use node.js 4.5 and drop node.js 0.10.x.
I will update to the new instuctions really soon.

**Comment by j8r** [comment]
Tell me if you still continue to experience issues, thank you!

**Comment by abers** [comment]
Removed everything and did clean install of it all again. Unfortunately the issue persists. Rocket.Chat installs OK and shows up fine in htop but get 'can not connect' error when trying to access the webpage. Noticed by doing systemctl status a few times that Rocket.Chat seems to be restarting every four minutes or so. Could it potentially be stopping / getting dropped due to lack of available RAM? Also have kodi, plex, and btsync running on same device and with those running alongside Rocket.Chat the RAM usage is pretty much a constant 100%. Since it originally worked for a couple of hours I am wondering if that was just luck when one of the other programs were not hogging as much RAM.

**Comment by abers** [comment]
Just stopped all other services and problem persists unfortunately.

**Comment by j8r** [comment]
It can be a RAM fully used and/or a memory leak, or maybe something else.
You can watch the RAM status with `free -m`, start Rocke.Chat and watch again and again to see how it evolve.
If you can connect to Rocket.Chat web UI even a second this will a not an installation or network problem.
Note that I've keeped Node.js 6.0 and choose to don't install and use the supported Node.js 4.5 because it appears to work. It could be that eventually.
