### ISSUE TITLE
installing Gogs installs RocketChat

### ISSUE THREAD

**Issue by ideomux** [j8r/DPlatform#21]
![screenshot from 2016-09-28 15-54-10](https://cloud.githubusercontent.com/assets/15969369/18935438/ebfdd322-8594-11e6-8f7a-66231b301cd9.png)

**Comment by j8r** [comment]
Wow weird! I can't reproduce it, I haven't this problem on my side.
Can you check please:
If you haven't a Rocket.Chat instance already running (on the port 3000).
The `systemctl status gogs -l` to see if gogs runs well.
