### ISSUE TITLE
IPv6 selectioned by default instead IPv4

### ISSUE THREAD

**Issue by Antexa** [j8r/DPlatform#22]
Bonjour Bonjour, 

Il y a un problème de liaison entre le DPlatfrom.sh et le dossier app/lets-chat. 

De plus je n'arrive pas a détecter mon IPV4, il semble que l'IPV6 prenne le dessus.

**Comment by j8r** [comment]
Oui une adresse IPv6 est détectée, elle est sélectionnée à la place d'une éventuelle IPv4 par défaut.
Tu peux toujours aller dans "About" dans le menu principal pour avoir toutes les informations (y compris réseau) de ton système.
Si tu as deux adresses IPv6 et IPv4 et que seulle la dernière est utilisée/fonctionne, je vais devoir ajouter une manière de choisir.

**Comment by ghost** [comment]
Can you guys please talk English? Thanks!

**Comment by Antexa** [comment]
@wb9688 Sorry for this... 

I have noticed that J8r was french, so i wanted to speak french. 

The issue was talking about the IPv6 selectionned by default instead of IPv4. This can be a problem if we bind an app only on IPv6...

**Comment by j8r** [comment]
No worry you're both right. We should speak the best language to communicate. Indeed that depends of the people and the place.

Anyway, I will need to add a popup for this, the choice will be saved (IPv4 or IPv6) on `dp.cfg`.

Thanks to underline this problem, merci!
