### ISSUE TITLE
init.sh - startup errors

### ISSUE THREAD

**Issue by Rohlik** [j8r/DPlatform#23]
stderr/stdout contains this error messages after launch init.sh:
> fatal: unable to access 'https://github.com/DFabric/DPlatform-ShellCore/': Peer's Certificate has expired.
> Obtaining the IPv4 address from http://ip4.cuby-hebergs.com...
> done.
> nc: invalid option -- 'z'

And maybe because that I can't install new app due to "No Internet Connection" msg window.

**Comment by j8r** [comment]
Have you nevertheless access to an Internet connection? `git pull` seems to fail because of an expired certificate...
To check the Internet access, the command `nc -z g.co 443` is used, but the `nc` on your system doesn't recognize the `-z` argument. On what OS are you?

**Comment by Rohlik** [comment]
Yes, I have connection to internet. I can do anything, ping google or clone some git repo without problem.
I using RHEL 7.2 with nmap-ncat-6.40-7.el7.x86_64.

**Comment by j8r** [comment]
I change the `nc` command for `ping`, this will solve the warning. But for `Peer's Certificate has expired`, maybe try manually `git pull` or reinstall again DPlatform.
Have you succeed anyway to install apps?

**Comment by Rohlik** [comment]
Now is everything working like a charm! Thx for your time and work.
Now I have problem with Rocket.chat instalation, so I will create new issue.
PS: I also found easter egg :+1:

**Comment by ghost** [comment]
What's the easter egg? :P

**Comment by j8r** [comment]
Haha good job :+1: , you're one of the few that found it!
Rocket.Chat have recently moved to a new technology stack (meteor 1.4, node 4). This is not impossible that new issues appear. I will try it with CentOS 7 on Docker, thank you too to report this type of problems.

@wb9688 It hides in the DPlatform menus ;)

**Comment by j8r** [comment]
Fixed, thanks again @Rohlik !
