### ISSUE TITLE
ip address wont pull up anyhting when i enter it in on my browser

### ISSUE THREAD

**Issue by the-ashh** [j8r/DPlatform#26]
When i enter in the ip address that DPlatform tells me to enter in, this is what my browser says...

> This site can’t be reached
>
><ip_address> refused to connect.
>Try:
>Reloading the page
>Checking the connection
>Checking the proxy and the firewall
>ERR_CONNECTION_REFUSED

Help???
I have it all set up and the terminal says that everything is all good, so...

**Comment by j8r** [comment]
Hi.
Have you correctly configured the security on your network?
What OS do you use? You should check the network availability of your machine from another one (`ping`,`nc`...).

**Comment by P6g9YHK6** [comment]
I have the same problem.
OS: raspbian full, default browser, raspberry 2

cant access http://raspberrypi & http://raspberrypi:"port"
i have tried to set it as local and internet same result.

tried to reinstall the OS 3 times.
I will keep the raspberry like this in case any test is needed.

**Comment by j8r** [comment]
@ciborge @cooler9711 Have you tried with the local IP address instead of the hostname, as explained on the message box?

**Comment by P6g9YHK6** [comment]
yes i tried IP address,localhost,127.0.0.1,hostname, a different hostname.

same result "This site can’t be reached"

**Comment by j8r** [comment]
What app have you tried to install? And from which machine have you tried to connected to?

**Comment by P6g9YHK6** [comment]
tried : jitsy, wordpress, rocket.chat, etherpad, tried on the Raspberry directly & an android.

**Comment by j8r** [comment]
Try to reinstall, for example, Etherpad with "Internet access" selected before, and access it with `localhost:9001`.

**Comment by P6g9YHK6** [comment]
same result.

**Comment by j8r** [comment]
Can you print me the output of `systemctl status etherpad -l` ?

**Comment by j8r** [comment]
> 510 002 247 e4jq94 

Sorry, whats is this?

**Comment by P6g9YHK6** [comment]
a teamviewer id & password if you want to take the control :D but quick edit you comment to hide it x)

**Comment by j8r** [comment]
We can use [Chrome Remote Desktop](https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp) (`apt install chromium-browser`). You can send me the number :) and then delete

**Comment by P6g9YHK6** [comment]
i cant connect with a google account "service unavailable".
but this is the log:
pi@raspberrypi:~ $ systemctl status etherpad
● etherpad.service - Etherpad Server
   Loaded: loaded (/etc/systemd/system/etherpad.service; enabled)
   Active: active (running) since Tue 2016-11-29 13:42:12 UTC; 1s ago
 Main PID: 6436 (node)
   CGroup: /system.slice/etherpad.service
           └─6436 /usr/bin/node /home/etherpad/node_modules/ep_etherpad-lite/node/server.js...
pi@raspberrypi:~ $

**Comment by j8r** [comment]
This is a lowercase L, not a 1. Any way, not really needed here.
>"service unavailable"

Can we use [RealVNC](https://www.realvnc.com/download/vnc/raspberrypi/)?

**Comment by ciborge** [comment]
it is installed and active but i did not tested. so i cant really tell if it will work on my network (university).
http://10.34.219.223:5800.

still teamviewer is tested and working :D 

510 002 247
1m5xz7

**Comment by j8r** [comment]
Can't connect

**Comment by j8r** [comment]
Still can't connect

**Comment by P6g9YHK6** [comment]
the PI is frozen the extraction is working but there is a big load on the cpu. you can comeback now maybe.

**Comment by P6g9YHK6** [comment]
na forget about it will tell when it is completely over.

**Comment by j8r** [comment]
I need to wait because i try too much :(

**Comment by P6g9YHK6** [comment]
even the mouse is frozen so nothing to do now x)

**Comment by j8r** [comment]
Can we write on Mumble? My address is `jrei.ch`. You can use Plumble on android

**Comment by P6g9YHK6** [comment]
but still to get back where we left i dont think there is anything wrong with the network. it is not the first time i setup a webserver and i had no problem of this kind at all.

**Comment by j8r** [comment]
There is an issue with etherpad, but other installation should works anyway. Yes that's problematic.

**Comment by j8r** [comment]
Thank you very much @ciborge . Rocket.Chat, Etherpad and Wordpress should work now.
I would be glad to work with you on the Jitsi installation, and finalize the automated script :)
