### ISSUE TITLE
possible addition of gitea?

### ISSUE THREAD

**Issue by persianphilosopher** [j8r/DPlatform#29]
Thank you for your slim and efficient platform. It is the only one that made Gogs just work!

Although I use Gogs from your platform, I was wondering whether you have considered adding [gitea](https://gitea.io/en-us/) as well. It is a community fork of gogs and should not be too much trouble on your end (or at least I hope not). But it is more actively developed and it looks really promising. 

Anyway, just a suggestion and I understand if it does not suit your roadmap. Thanks again.

**Comment by j8r** [comment]
I didn't know Gitea, good idea! I've already replaced Shout by its fork [TheLounge](https://thelounge.github.io/) before, for some reasons which are close to [those of Gitea](https://blog.gitea.io/2016/12/welcome-to-gitea/) (i.e. the original author who controls its project).

I will add this project besides Gogs, thanks for this good suggestion 👍

**Comment by persianphilosopher** [comment]
that's wonderful of you. thank you
