### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by tbeason** [j8r/DPlatform#31]
Just wanted to leave my feedback as I've found this to be a nice tool.

- My install of netdata always fails near the end, when copying the file from system to /etc/systemd

- Install of FreshRSS just fails, sorry I can't give more info than that. Don't have the error in my terminal window anymore.

- Wekan install fails, citing a syntax error in MongoDB.sh

I'm running Jessie Lite on a Rpi2

**Comment by j8r** [comment]
Thanks for the feedback! I test and fix this ASAP

**Comment by j8r** [comment]
I didn't have any problem with the FreshRSS installation, it's likely to be a reverse proxy issue with your Nginx configuration (that is generated by the script).
