### ISSUE TITLE
Display actual port number after install

### ISSUE THREAD

**Issue by ghost** [j8r/DPlatform#33]
Would it be possible to display the actual port number after installing an app?
Currently, the window after the installation displays the correct host name, but not the chosen port.

**Comment by j8r** [comment]
What app have you installed? Anyway I'm working actually on a new release "v1.0" of DPlaftorm that have this feature, this informations will be on a yaml file.

**Comment by ghost** [comment]
Great news! Found this behaviour after installing EtherCalc, same goes for Etherpad at least I guess

**Comment by j8r** [comment]
I add also that a `dpcli` command will replace the GUI based on `whiptail`. The port and domain will be options of `dpcli`.
Thanks I see what's wrong, I go fixing this, thanks!

**Comment by j8r** [comment]
Fixed - just the variable `$port` instead of the "static" default port number. I've also fixed the not empty issue for `/home/etherpad`, at least. The script don't create a default home for the user, only the `git clone` do.

**Comment by ghost** [comment]
Awesome! I think the empty issue was on my side, I was using a root terminal rather than sudo, maybe that was a problem there.
