### ISSUE TITLE
Git cloning fails because target directory isn't empty

### ISSUE THREAD

**Issue by ghost** [j8r/DPlatform#34]
Cloning a repository into a new created /home/user path fails because .bash_logout .bashrc and .profile are being created with the user creation.
Possible solutions:

- Edit the documentation, users have to tell their OS not to create those files
- Edit the scripts so those files get deleted (rm -rf /home/app/.* would be the quick and dirty variant here)
- Circumvent the issue using git init ... (see [here](http://stackoverflow.com/a/18999726))

Using OS: Ubuntu Server 16.10

**Comment by ghost** [comment]
My fault, was in a root terminal rather than using sudo for this installation.

**Comment by j8r** [comment]
This solve the issue to run as sudo?!

**Comment by ghost** [comment]
Well, at least other apps installed flawlessly, so that's probably the reason.
I can test it again tomorrow, but it might not be a bad idea to clear the directory or create a subdirectory for the clone.

**Comment by j8r** [comment]
I will test also on my side. Be free to make a PR and fix like I've done with etherpad if you found this error again :).
The `-m` option of `useradd` create a home directory from a skeleton, that have dotfiles. So I think a good solution it to remove this option, and add after the `git clone` command the app folder name in question.
