### ISSUE TITLE
too many request

### ISSUE THREAD

**Issue by vBlackOut** [j8r/DPlatform#38]
Hi, julien the script send to many request on server cuby hebergs 2/5 requests per minutes for check ip address.

look here 

---------------------------------------Log Connexion----------------------------------------
Date  : 13-06-2017 15:55:10
Call URL  : /
SERVER_PROTOCOL : HTTP/1.1
REQUEST_METHOD : GET
HTTP_CLIENT_RESOLVER :  (82.255.32.23) and port 52646
HTTP_ACCEPT_ENCODING : 
HTTP_CONNECTION : 
HTTP_USER_AGENT : curl/7.54.0
HTTPS : 
GET DATA : 
SESSION DATA : 
  ville => Viane
  region => Midi-Pyr&eacute;n&eacute;es
  pays => France
  ISP => AS12322 Free SAS
COOKIE DATA : 
---------------------------------------End Log Connexion--------------------------------------

---------------------------------------Log Connexion----------------------------------------
Date  : 13-06-2017 15:55:27
Call URL  : /
SERVER_PROTOCOL : HTTP/1.1
REQUEST_METHOD : GET
HTTP_CLIENT_RESOLVER :  (82.255.32.23) and port 55841
HTTP_ACCEPT_ENCODING : 
HTTP_CONNECTION : 
HTTP_USER_AGENT : curl/7.54.0
HTTPS : 
GET DATA : 
SESSION DATA : 
  ville => Viane
  region => Midi-Pyr&eacute;n&eacute;es
  pays => France
  ISP => AS12322 Free SAS
COOKIE DATA : 
---------------------------------------End Log Connexion--------------------------------------

---------------------------------------Log Connexion----------------------------------------
Date  : 13-06-2017 15:55:28
Call URL  : /
SERVER_PROTOCOL : HTTP/1.1
REQUEST_METHOD : GET
HTTP_CLIENT_RESOLVER :  (82.255.32.23) and port 51653
HTTP_ACCEPT_ENCODING : 
HTTP_CONNECTION : 
HTTP_USER_AGENT : curl/7.54.0
HTTPS : 
GET DATA : 
SESSION DATA : 
  ville => Viane
  region => Midi-Pyr&eacute;n&eacute;es
  pays => France
  ISP => AS12322 Free SAS
COOKIE DATA : 
---------------------------------------End Log Connexion--------------------------------------

---------------------------------------Log Connexion----------------------------------------
Date  : 13-06-2017 15:55:38
Call URL  : /
SERVER_PROTOCOL : HTTP/1.1
REQUEST_METHOD : GET
HTTP_CLIENT_RESOLVER :  (82.255.32.23) and port 55773
HTTP_ACCEPT_ENCODING : 
HTTP_CONNECTION : 
HTTP_USER_AGENT : curl/7.54.0
HTTPS : 
GET DATA : 
SESSION DATA : 
  ville => Viane
  region => Midi-Pyr&eacute;n&eacute;es
  pays => France
  ISP => AS12322 Free SAS
COOKIE DATA : 
---------------------------------------End Log Connexion--------------------------------------

---------------------------------------Log Connexion----------------------------------------
Date  : 13-06-2017 15:55:39
Call URL  : /
SERVER_PROTOCOL : HTTP/1.1
REQUEST_METHOD : GET
HTTP_CLIENT_RESOLVER :  (82.255.32.23) and port 52389
HTTP_ACCEPT_ENCODING : 
HTTP_CONNECTION : 
HTTP_USER_AGENT : curl/7.54.0
HTTPS : 
GET DATA : 
SESSION DATA : 
  ville => Viane
  region => Midi-Pyr&eacute;n&eacute;es
  pays => France
  ISP => AS12322 Free SAS
COOKIE DATA : 
---------------------------------------End Log Connexion--------------------------------------

**Comment by j8r** [comment]
Hi, what would you suggest?

**Comment by vBlackOut** [comment]
check timestamp and limit 
time_file < (real_time-60):
       False
else:
       True
log the request for other temporary file.

**Comment by j8r** [comment]
Your site is no longer the default used, I close the issue.
