### ISSUE TITLE
How to access installations when completed?

### ISSUE THREAD

**Issue by brylie** [j8r/DPlatform#41]
I have installed an instance of NodeBB, but can't figure out how to access it over the network. Neither Apache nor Nginx appear to be installed, so I can't look up any reverse proxy configuration. How do I configure the domain/path, so that I can access applications once installed?

**Comment by j8r** [comment]
There are no need for a reverse proxy/http server – this is a Node.js application.
The script should have printed [this content](https://github.com/DFabric/DPlatform-ShellCore/blob/master/apps/NodeBB.sh#L95) in a box after the installation.

It has been a long time I haven't tested the installation of NodeBB, and the instructions might have changed since.

This is time to try this script again.
Can you check if the nodebb.service is ok, if you have one?
```
systemctl restart nodebb
systemctl status nodebb -l
```

**Comment by brylie** [comment]
I will double check that the service is running, as you recommend. How can I set it up to listen on port 443 via HTTPS?

In effect, I am installing this application for a community, so I don't expect people to enter a port number in the URL.

**Comment by j8r** [comment]
The simplest way to do this is to setup a Caddy server. It's setup script works well here if you want to install it.
Depending of the version of your systemd (>=v229), you may need to uncomment in `/etc/systemd/system/caddy.service`
```
;CapabilityBoundingSet=CAP_NET_BIND_SERVICE
;AmbientCapabilities=CAP_NET_BIND_SERVICE
```
I will add this feature in the script.

**Comment by brylie** [comment]
OK, cool. Yeah, having a ready-to-go webapp after the automated installation is the goal I was hoping for. 

Great project!

**Comment by j8r** [comment]
Thanks! Indeed, but the magic behind is not simple.
I work on a v2 that will bring this, will be ready I think in the fall of 2017.
But for now, the goal of this scripts is to install & setup the application, that's it (for now).
Domain names, TLS certs and reverse proxying are other optional setups to do atop of the application.
In the future, even the DNS entries could be created automatically using the APIs of the providers.

**Comment by j8r** [comment]
The NodeBB installation is OK for me.
Just be aware when the script execute their CLI wizard, it asks some important informations like the database, the domain name, passwords etc.
