### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by BetaStacks** [j8r/DPlatform#47]
I did a fresh install of Raspbian Lite, ssh into pi, installed Rocket.chat, and am unable to access it via my internal ip. 10.0.1.14:3004.

A status check shows rocket.chat and mongodb are running.

**Comment by j8r** [comment]
Hi. What return `systemctl status rocket.chat -l`?.
Can you ping 10.0.1.14?
Finally, if in your PI a `wget -qO- localhost:3004` return something, you will need to configure your network.

**Comment by BetaStacks** [comment]
Ended up figuring it out today. The issue was that the local mongo database wasnt starting before the rocket.chat server

**Comment by j8r** [comment]
Normally the `mongod.service` starts before, with this lines on the Roket.Chat systemd service:
```
Wants=mongod.service
After=network.target mongod.service
```
