### ISSUE TITLE
Rocket Chatt Https?

### ISSUE THREAD

**Issue by BetaStacks** [j8r/DPlatform#48]
Hello, I have rocket chat running on my raspberry pi. It works on http but not on https. Is there something in Rocket chat that I need to configure or is it simply a apache configuration?

**Comment by j8r** [comment]
The official [Rocket.Chat docs](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#configuring-ssl-reverse-proxy) explains what to do.
Yes, Rocket.Chat will be behind a reverse proxy that do the TLS negociation.

Here you will need to modifiy `ROOT_URL=http://localhost:3004` to something like `ROOT_URL=https://your_hostname.com` in `/etc/systemd/system/rocket.chat.service`.
