### ISSUE TITLE
MongoDB outdated and doesnt work with RocketChat.

### ISSUE THREAD

**Issue by BetaStacks** [j8r/DPlatform#49]
Last night I tried doing a clean install using just the tools in this script. I found that RocketChat would not work with the version on MongoDB provided here. I had to follow the instructions at http://andyfelong.com/downloads/core_mongodb.tar.gz for 3.0.9 and then use DPlatform to install rocketchat.

**Comment by j8r** [comment]
We was using his build before a mongodb build was available in the Debian Stretch repository.
Maybe it's just the name of the service, I remember an issue like this, `mongodb.service` instead of `mongod.service`.

**Comment by j8r** [comment]
Should fix the issue.
By the way RC worked before, but the DB just didn't start with it right?
