### ISSUE TITLE
Error installing Ajenti

### ISSUE THREAD

**Issue by alexborisov** [j8r/DPlatform#5]
Trying to install Ajenti immediately returns `Could not detect OS` and exits. Ajenti is listed as installed in DPlatform, but obviously doesn't work. Tested on RPi 3 _Raspbian_.

**Comment by j8r** [comment]
The Ajenti installation depends of this command provided by the project [docs](http://docs.ajenti.org/en/latest/man/install.html#automatic-installation): `curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh > install.sh && bash install.sh`, [source](https://github.com/ajenti/ajenti/blob/master/scripts/install.sh).
This not a problem of DPlatform itself. Ajenti with its auto-installation script officially supports Raspbian. So if you encounter some troubles, you can report an issue on the [Ajenti GitHub project](https://github.com/ajenti/ajenti).

**Comment by alexborisov** [comment]
OK thanks!
