### ISSUE TITLE
rocket chat no main.js in /var/www/rocketchat

### ISSUE THREAD

**Issue by BetaStacks** [j8r/DPlatform#50]
I just installed Rocket Chat on my Raspberry Pi.  Rocket chat isnt starting  it says that the main.js file is missing.

in /var/www/rocketchat there is: node_modules  and rocket.chat.tar.gz

I tried:
tar -xvzf rocket.chat.tar.gz

and received:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by BetaStacks** [comment]
@j8r  Just to clarify, I used DPlatform-ShellCore to perform the install.

**Comment by j8r** [comment]
Of course, `dppm` will be released soon, I need to add more applications and compile it statically.

The download url has changed. When executing a `wget`, the redirection doesn't perform correctly. Fixed now, thanks!

**Comment by BetaStacks** [comment]
Sweet! You're doing an amazing job! Thank you for all your work in this tool.
