### ISSUE TITLE
Add Cloud9

### ISSUE THREAD

**Issue by ghost** [j8r/DPlatform#7]
Could you please add [Cloud9](https://github.com/c9/core)?

**Comment by j8r** [comment]
Thanks for the suggestion! I just try it, and looks nice but this is the Cloud9 3.0 SDK for Plugin Development. Thus I don't think this is suitable for production deployment. Maybe it would be better to use IDEs based on it, or other alternatives?

**Comment by ghost** [comment]
[Plunker](https://github.com/filearts/plunker_www) is an alternative, but it's webdev-only and I don't how production-ready it is.

**Comment by j8r** [comment]
Anyway i like very much the idea of a web based IDE. That's why i've worked on [Wide](https://github.com/b3log/wide) support. I don't know lots of alternatives to this solutions. There is also [Codiad](http://codiad.com/), but it is less advanced, and based on PHP5.

**Comment by ghost** [comment]
I also like the idea of a web-based IDE. It's unfortunate that Wide only Go supports. I don't know alternatives either. But I don't think Codiad is a real IDE as you can't run your code.

**Comment by j8r** [comment]
I haven't found any as featured alternatives to Cloud9. Despite being in alpha and designed for development, it's nevertheless a pretty good solution. So I plan to support it in the near feature, when I will find some time. Thanks for the suggestion!

**Comment by ghost** [comment]
Yeah, btw you can load a workspace by adding ?w=/path/to/workspace&token=random_token to the url (see https://github.com/c9/core/blob/master/plugins/c9.vfs.standalone/standalone.js#L262) so it would be handy to make a wrapper for that…

**Comment by ghost** [comment]
I'm currently working on a Cloud9 workspace manager:

![Screenshot](https://cloud.githubusercontent.com/assets/9780201/16685827/024b74d0-450e-11e6-8c39-67c6453d39c3.png)

**Comment by j8r** [comment]
Great! It will be a pleasure to add your workspace manager along with Could9.

**Comment by j8r** [comment]
@wb9688 I've finally added Cloud9, can you review this? I haven't extensively tested this script, and certainly lacks of Raspberry Pi support. Feel free to send me a PR, thank you!
