### ISSUE TITLE
Issues while installing Rocket.Chat

### ISSUE THREAD

**Issue by GorgiAstro** [j8r/DPlatform#8]
Hello,

I have noticed several issues while installing Rocket.Chat, and I have fixed them. Attached are the logs.
- The command "whiptail" is mistyped "whitpail" in several bash scripts, for example in service.sh:67, Meteor.sh:3-6, MongoDB.sh:4 or in Rocket.Chat.sh:5.
- In Rocket.Chat:97, the wget command misinterprets the arguments, and understands the URL to be https://cdn-download.rocket.chat/build/rocket.chat-pi-develop.tgz%20-O%20rocket.chat.tgz .

**Comment by j8r** [comment]
Hi, thank you a lot! I've done a big refactoring, and several issues like this appear like a syntax error in a search and replace action.
